baseURL: "https://rokiyama.dev/"
languageCode: "ja"
title: "rokiyama.dev"
theme: "PaperMod"

defaultContentLanguage: "ja"

params:
  homeInfoParams:
    Title: "rokiyama.dev"
  socialIcons:
    - name: github
      url: "https://github.com/rokiyama"
    - name: twitter
      url: "https://twitter.com/rokiyama_dev"
    - name: rss
      url: "index.xml"
  showPostNavLinks: true
  hideSummary: true
  dateFormat: 'Mon Jan 2, 2006'
  showFullTextinRSS: true

  googleAnalytics: G-TBC439E3VT
