baseURL: "https://okiyama.dev/"
languageCode: "ja"
title: "okiyama.dev"
theme: "PaperMod"
pagination:
  pagerSize: 100
titleCaseStyle: none

defaultContentLanguage: "ja"

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: google_search
      name: Search(Google)
      url: https://www.google.com/search?q=site%3Aokiyama.dev+&ie=UTF-8
      weight: 30
    - identifier: source
      name: Source
      url: https://github.com/rokiyama/okiyama.dev
      weight: 40

params:
  homeInfoParams:
    Title: "okiyama.dev"
  socialIcons:
    - name: github
      url: "https://github.com/rokiyama"
    - name: x
      url: "https://twitter.com/okiyama_rei"
    - name: rss
      url: "index.xml"
  showPostNavLinks: true
  hideSummary: true
  dateFormat: "2006/1/2 (Mon) 15:04 MST"
  showFullTextinRSS: true
  showtoc: true
  tocopen: true

  googleAnalytics: G-TBC439E3VT

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
